# Site settings
title: Plop
email: plop@plop.com
description: "blablabla"
baseurl: ""
url: "https://plop.com"
logo: /img/logo.png

defaults:
  - scope:
      path: ""
    values:
      image: /img/logo.png

# Build settings
markdown: kramdown

gems:
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-autoprefixer

exclude:
  - vendor
  - README.md
  - circle.yml
  - CONTRIBUTING.md
  - Dockerfile
